### PR TITLE
Update SUPPORTED.md

### PR DESCRIPTION
**Pull request by miquelmarti**
It works nicely on my machine, thanks!

### CODE REVIEW

**Comment by stephenlacy** [comment]
That entry was provided by another contributor, can you add a new line with your system OS and machine info instead of editing his? Thanks

**Comment by miquelmarti** [comment]
Well sure, but it would say the same and adding this specific machine...

**Comment by stephenlacy** [comment]
Yeah, but that was someone else who may have a different machine.
I don't think your kernel version is exactly the same as what the other contributor had: `4.13.0-32-generic`

**Comment by miquelmarti** [comment]
You are right, I had checked and thought everything was exactly the same, but it's `4.13.0-32-generic` so I'm gonna add a new entry :wink:

**Comment by stephenlacy** [comment]
thanks!

**Pull request merged**
