### PR TITLE
Add support for MacOS

### PR DESCRIPTION
**Pull request by AutinMitra**
Just changed some of the scripts to start and build, also may fix the node-hid mismatch problem.

### CODE REVIEW

**Comment by stephenlacy** [comment]
Nice, I'll merge once I test on linux/macos

**Comment by AutinMitra** [comment]
Nice thing to note too is that macOS (at least I don't think so) needs sudo/admin for hid (as the compiled app starts up fine without admin)

**Comment by timofonic** [comment]
@stevelacy New release soon? Will there be a new WIN64 build too?

PS: Offtopic... Do you know about MSIHiddenFun too?

**Comment by stevelacy** [comment]
I do not know of MSIHiddenFun

**Comment by erikbdev** [comment]
Awesome, I would also want to help with this compatibility for mac, but I don't know if it's still being worked on. Regardless, I will add my changes too.

**Comment by stephenlacy** [comment]
Sorry for the long delay, I just tested it on macos (crazy :smile:)

**Pull request merged**
